default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bodymeasures_development

test:
  <<: *default
  database: bodymeasures_test

production:
  <<: *default
  database: bodymeasures_production
  username: bodymeasures
  password: <%= ENV['BODYMEASURES_DATABASE_PASSWORD'] %>
